---
- name: restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted

- name: restart cloudwatch agent
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: restarted
