---
all:
  children:
    webservers:
      hosts:
        dev-bastion-host:
          ansible_host: 13.205.92.122
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/terraform-ansible-automation-infrastructure.pem
