---
- name: Install security packages
  ansible.builtin.apt:
    name:
      - fail2ban
      - unattended-upgrades
    state: present

- name: Configure SSH Hardening - Disable Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin {{ permit_root_login }}'
  notify: restart sshd

- name: Configure SSH Hardening - Disable Password Auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication {{ password_authentication }}'
  notify: restart sshd

- name: Configure Fail2Ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Enable unattended security updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    mode: '0644'
